### ISSUE TITLE
Auth suggestions

### ISSUE THREAD

**Issue by Sroka** [code-helix/slatekit#2]
Hi guys, thanks for all the good work being done here. I am waiting anxiously for 1.0 release :) 
I have a question regarding auth in slatekit. In the [docs](http://www.slatekit.com/kotlin-mod-auth.html) it is written that you leave handling auth to other libraries. While this is good idea, maybe you have some suggestions on what would be be the best library choice for quickly implementing it both on server and client side alike.

For example, in case of [Firebase](https://firebase.google.com/) the selling point for me was drop in auth solution including social auth and [client side libraries](https://github.com/firebase/FirebaseUI) they prepared. With this I am able to include auth in my app in around 5 minutes total.

Slatekit could really benefit from having some ready solutions or samples regarding auth

**Comment by kishorereddy** [comment]
Hey, thanks for the feedback! Your suggestion about including a drop-in implementation for Auth in Slate Kit makes sense. Actually, there is some basic Auth stuff present, but its just not fully documented 
and complete ( will make this available soon ). However, we will definitely prioritize this in the upcoming releases.

So about the auth.... Slate Kit has a couple of things available, as both components and some examples in the Sample Apps. I'm assuming you're specifically requiring Auth in some server APIs. What is available right now is a default Auth base class that you can implement 1-2 core methods to get auth behavior. However, this is currently dependent on using Slate Kit APIs. ( Now that you mention it, it may be worth while for us to split that out into a separate module. )

## Server / APIs
Here are some links on the overview of the API approach and the Auth.
Basically, there are 2 ways ( api keys & roles ) you can do some type of auth in Slate Kit APIs

1. **Overview**
Here is the overview of the API setup ( also see links to the samples below )
http://www.slatekit.com/kotlin-core-apis.html

2. **Keys**: You can setup the APIs to use api-keys based security. 
This is the simple approach which allows for X number of API keys linked to roles in which the api-keys are used by more than 1 user. 
http://www.slatekit.com/kotlin-core-apis.html#api-security 
Also refer to the Samples below for more info.

3. **Roles**: You can setup the APIs to use roles based security. 
This is probably what you're looking for where you have a token per user and the token somehow links roles to 1 specific user. There is an example of implementing this in the Sample app ( again refer to sample apps below ). But this basically involves implementing just 1-2 methods of the **Auth.kt** class see link below.

4. **Suggestions**: For using any external Auth implementations.
Slate Kit APIs can be used on both the command line and in the Web API Server. If you're using the server, it is a thin wrapper on top of the Spark Java Web Server. So basically, in the next version 0.9.6 ( coming out next week actually), we expose more of underlying spark server during setup so you can configure it what ever way. My suggestion here would be to lookup what Spark Server recommends for Auth. I would also look for any suggestions to Auth libraries in the github "Awesome Kotlin" pages

## Samples
1. **Sample server**: Here is a sample server using the Slate Kit API approach with the auth setup 
https://github.com/code-helix/slatekit/blob/master/src/apps/kotlin/slatekit-sampleapps/sampleapp-server/src/main/kotlin/slatekit/sampleapp/server/SampleAppServer.kt

2. **AppAuth**: A sample implementation of the auth
https://github.com/code-helix/slatekit/blob/master/src/apps/kotlin/slatekit-sampleapps/sampleapp-core/src/main/kotlin/slatekit/sampleapp/core/common/AppAuth.kt

3. **Auth.kt**: The default auth base class for the APIs/Server
https://github.com/code-helix/slatekit/blob/master/src/lib/kotlin/slatekit-apis/src/main/kotlin/slatekit/apis/core/Auth.kt
